---
cluster: "{{ cluster_name }}"
attributes:
  bc_num_hours:
    value: 1

  bc_num_slots:
    label: Number of CPU
    value: 1
    min: 1
    max: 24
    step: 1

  bc_num_mems:
    widget: "number_field"
    label: Memory per CPU
    value: 4
    min: 1
    max: 128
    step: 1

  bc_partition:
    widget: select
    label: Partition
    options:
      - [ "low", "low" ]

  version:
    widget: select
    label: "R version"
    help: "This defines the version of R you want to load."
    options:
      # Define functioning R version overloads using a colon after the module load statement
{% for ver in r_versions %}
      - [ "{{ ver.full }}", "rstudio_singularity/{{ ver.full }}"]
{% endfor %}
form:
  - version
  - bc_num_hours
  - bc_partition
  - bc_num_slots
  - bc_num_mems
  - bc_email_on_started
