---
- name: Get OpenHPC repo
  yum: name={{ openhpc_release_rpm }} state=present update_cache=true

- name: Install Copr plugin for yum
  yum: name=yum-plugin-copr state=present update_cache=true
  when: enable_copr == true

- name: enable Copr Repos
  shell: yum -y copr enable "{{ item.repo_name }}"
  with_items: "{{ copr_repos }}"
  when: enable_copr == true and inventory_hostname in item.host

- name: Install dependencies-nfs-utils, ohpc packages, ntp and other required tools.
  yum: name={{ item }} state=installed update_cache=true
  with_items:
    - nfs-utils
    - ohpc-base-compute
    - slurm-ohpc
    - zsh
    - git
    - vim
    - tmux
    - ruby

- name: Mount /home, /opt/ohpc/pub from OHPC node
  mount:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: nfs
    opts: nfsvers=3,nodev,noatime
    state: mounted
  with_items:
    - { path: "/home", src: "{{ headnode_private_ip }}:/home" }
    - { path: "/opt/ohpc/pub", src: "{{ headnode_private_ip }}:/opt/ohpc/pub" }
