---

   - name: install OpenHPC base, warewulf, slurm server, and compiler packages
     yum:
       name: [ 
               "ohpc-base",
               "ohpc-warewulf",
               "ohpc-slurm-server",
               "lmod-defaults-gnu-openmpi-ohpc",
               "openmpi-gnu-ohpc", 
               "gnu-compilers-ohpc"
             ]
       state: latest

   - name: yum update
     yum: name=* state=latest update_cache=yes

   - name: add slurm user
     user: name=slurm state=present system=yes

   - name: create slurm.conf
     template: src=slurm_conf.j2 dest=/etc/slurm/slurm.conf

   - name: create slurmdbd.conf
     template: src=slurmdbd_conf.j2 dest=/etc/slurm/slurmdbd.conf

   - name: put the sacctmgr config in /etc/slurm
     copy: src=xcbc-example.cfg dest=/etc/slurm/sacctmgr-heirarchy.cfg

   - name: set the gres.conf on the master
     copy: src=gres.conf dest=/etc/slurm/gres.conf

   - name: create the slurmdbd log file
     file: path=/var/log/slurmdbd.log state=touch owner=slurm group=slurm

   - name: insert rhel-xcbc WW template
     copy: src=include-rhel-xcbc dest="{{ template_path }}include-rhel-xcbc"
 
   - name: fix the warewulf wwsh script... ARGH (line 29)
     lineinfile: 
       dest: /bin/wwsh
       insertafter: '^\$ENV\{\"PATH\"\}'
       line: "delete @ENV{'PATH', 'IFS', 'CDPATH', 'ENV', 'BASH_ENV'};"
       state: present

   - name: fix the warewulf wwnodescan script... ARGH (line 96)
     lineinfile: 
       dest: /bin/wwnodescan
       insertafter: '^\$ENV\{\"PATH\"\}'
       line: "delete @ENV{'PATH', 'IFS', 'CDPATH', 'ENV', 'BASH_ENV'};"
       state: present

 
   - name: initialize slurmdb databases
     mysql_db:
       name: "{{ slurm_acct_db }}"
       state: present

   - name: create slurmdb user
     mysql_user:
       name: "{{ slurmdb_sql_user }}"
       password: "{{ slurmdb_sql_pass }}"
       priv: "{{ slurm_acct_db }}.*:ALL"
       state: present

   - name: start and enable munge
     service: 
       name: munge
       state: started
       enabled: yes

   - name: start and enable slurmdbd
     service: 
       name: slurmdbd
       state: started
       enabled: yes

   - name: load sacctmgr config
     command: sacctmgr -i load /etc/slurm/sacctmgr-heirarchy.cfg

   - name: start and enable slurmctld
     service: 
       name: slurmctld
       state: started
       enabled: yes

