---
name: RStudio Server
category: Interactive Apps
subcategory: Servers
role: batch_connect
description: |
  This app will launch [RStudio Server] an IDE for [R].

  [RStudio Server]: https://www.rstudio.com/products/rstudio-server/
  [R]: https://www.r-project.org/
