---
- name: Enable the Software Collections repository
  yum:
    name: "centos-release-scl"
    state: present
  when: ansible_distribution == "CentOS"

- name: Enable the Software Collections repository on RHEL 7
  rhsm_repository:
    name: rhel-server-rhscl-7-rpms
    state: enabled
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version == '7'

- name: Fix failing SCL RH7 repo with static baseurl
  ini_file:
    path: /etc/yum.repos.d/CentOS-SCLo-scl-rh.repo
    section: centos-sclo-rh
    option: baseurl
    #value: http://www.gtlib.gatech.edu/pub/centos/7/sclo/$basearch/rh/
    value: http://mirror.centos.org/centos/7/sclo/x86_64/rh/
    backup: yes

- name: Fix remove mirrorlist from SCL RH7
  ini_file:
    path: /etc/yum.repos.d/CentOS-SCLo-scl-rh.repo
    section: centos-sclo-rh
    state: absent
    option: mirrorlist
    backup: no

- name: Add Open OnDemandâ€™s repository hosted by the Ohio Supercomputer Center
  yum:
    name: "{{ ood_rpm_repo }}"
    state: present

- name: Install OnDemand and all of its dependencies
  yum:
    name: "ondemand"
    state: present

- name: Create clusters.d directory
  file:
    path: /etc/ood/config/clusters.d
    state: directory

- name: Add cluster configuration files
  template:
    src: cluster.yml
    dest: /etc/ood/config/clusters.d/{{ cluster_name }}.yml

- name: Create interactive desktop settings directory
  file:
    path: /etc/ood/config/apps/bc_desktop
    state: directory

- name: Add interactive desktop settings
  template:
    src: bc_desktop/cluster.yml
    dest: /etc/ood/config/apps/bc_desktop/{{ cluster_name }}.yml

- name: Create interactive desktop job submit script directory
  file:
    path: /etc/ood/config/apps/bc_desktop/submit
    state: directory

- name: Add interactive desktop job submit script
  template:
    src: bc_desktop/submit.yml.erb
    dest: /etc/ood/config/apps/bc_desktop/submit/submit.yml.erb

- name: Enable reverse proxy
  replace:
    path: /etc/ood/config/ood_portal.yml
    regexp: '{{ item.regexp }}'
    replace: '{{ item.replace }}'
  with_items:
      - { regexp: "^#?host_regex:.*$", replace: "host_regex: '{{ compute_node_glob }}'" }
      - { regexp: "^#?node_uri:.*$", replace: "node_uri: '/node'" }
      - { regexp: "^#?rnode_uri:.*$", replace: "rnode_uri: '/rnode'" }

- name: Stage http authz file for ood
  copy:
    src: htpasswd
    dest: /opt/rh/httpd24/root/etc/httpd/.htpasswd
    owner: root
    group: root
    mode: 0644

- name: Build the updated Apache config
  command: /opt/ood/ood-portal-generator/sbin/update_ood_portal
  ignore_errors: yes
