---
- name: Enable the Software Collections repository
  yum:
    name: "centos-release-scl"
    state: present

- name: Add Open OnDemandâ€™s repository hosted by the Ohio Supercomputer Center
  yum:
    name: "https://yum.osc.edu/ondemand/1.3/ondemand-release-web-1.3-1.el7.noarch.rpm"
    state: present

- name: Install OnDemand and all of its dependencies
  yum:
    name: "ondemand"
    state: present

- name: Create clusters.d directory
  file:
    path: /etc/ood/config/clusters.d
    state: directory

- name: Add cluster configuration files
  template:
    src: cluster.yml
    dest: /etc/ood/config/clusters.d/{{ cluster_name }}.yml

- name: Create interactive desktop settings directory
  file:
    path: /etc/ood/config/apps/bc_desktop
    state: directory

- name: Add interactive desktop settings
  template:
    src: bc_desktop/cluster.yml
    dest: /etc/ood/config/apps/bc_desktop/{{ cluster_name }}.yml

- name: Create interactive desktop job submit script directory
  file:
    path: /etc/ood/config/apps/bc_desktop/submit
    state: directory

- name: Add interactive desktop job submit script
  template:
    src: bc_desktop/submit.yml.erb
    dest: /etc/ood/config/apps/bc_desktop/submit/submit.yml.erb

- name: Enable reverse proxy
  lineinfile:
    path: /etc/ood/config/ood_portal.yml
    line: '{{ item }}'
  with_items:
    - "host_regex: '{{ compute_node_glob }}.localdomain'"
    - "node_uri: '/node'"
    - "rnode_uri: '/rnode'"

- name: Stage http authz file for ood
  copy:
    src: htpasswd
    dest: /opt/rh/httpd24/root/etc/httpd/.htpasswd
    owner: root
    group: root
    mode: 0644

- name: Build the updated Apache config
  command: /opt/ood/ood-portal-generator/sbin/update_ood_portal
  ignore_errors: yes
