---
- name: Enable the Software Collections repository
  yum:
    name: "centos-release-scl"
    state: present

- name: Add Open OnDemandâ€™s repository hosted by the Ohio Supercomputer Center
  yum:
    name: "https://yum.osc.edu/ondemand/1.3/ondemand-release-web-1.3-1.el7.noarch.rpm"
    state: present

- name: Install OnDemand and all of its dependencies
  yum:
    name: "ondemand"
    state: present

- name: Get OpenHPC repo
  yum: name={{ openhpc_release_rpm }} state=present update_cache=true

- name: Install dependencies-nfs-utils, ohpc packages, ntp and other required tools.
  yum: name={{ item }} state=installed update_cache=true
  with_items:
    - nfs-utils
    - ohpc-base-compute
    - ohpc-slurm-client
    - zsh
    - git
    - vim
    - tmux
    - ruby

- name: Mount /home, /opt/ohpc/pub from OHPC node
  lineinfile:
    path: /etc/fstab
    line: '{{ item }}'
  with_items:
    - "{{ headnode_private_ip }}:/home /home nfs nfsvers=3,nodev,nosuid,noatime 0 0"
    - "{{ headnode_private_ip }}:/opt/ohpc/pub /opt/ohpc/pub nfs nfsvers=3,nodev,noatime 0 0"

- name: Create clusters.d directory
  file:
    path: /etc/ood/config/clusters.d
    state: directory

- name: Add cluster configuration files
  template:
    src: cluster.yml
    dest: /etc/ood/config/clusters.d/{{ cluster_name }}.yml

- name: Stage http authz file for ood
  copy:
    src: htpasswd
    dest: /opt/rh/httpd24/root/etc/httpd/.htpasswd
    owner: root
    group: root
    mode: 0644

- name: Enable http service
  systemd:
    state: started
    name: httpd24-httpd
    enabled: yes

- name: Open port http/s
  firewalld:
    service: http
    permanent: true
    state: enabled

-  firewalld:
    service: https
    permanent: true
    state: enabled

- name: Disable SELinux Enforcement (permissive)
  selinux:
    policy: permissive
    state: permissive

- name: Set SELinux to permissive mode without reboot
  command: setenforce 0

# Implement warewulf file synchrnoization for cluster integration
# https://groups.io/g/OpenHPC-users/message/2084
# https://groups.io/g/OpenHPC-users/message/2405

# Discovery avoids having to hard code the ethernet device number
# it keys off the assigned static IP for the ood node and uses that
# to discover the ethernet device and mac address for the node
# adapted from: https://serverfault.com/a/852093
- name: discover ethernet address for ood internal network
  set_fact:
    ood_macaddress: "{{ hostvars[inventory_hostname]['ansible_' + item]['macaddress'] }}"
  when: hostvars[inventory_hostname]['ansible_' + item]['ipv4']['address'] == ood_ip_addr
  with_items:
    - "{{ hostvars[inventory_hostname]['ansible_interfaces'] }}"

- name: install warewulf file synchronization
  copy:
    src: warewulf
    dest: /
    owner: root
    group: root

# ensure script files are executable
- file:
    path: /warewulf/bin
    recurse: true
    mode: u+x,g+x

- name: create custom warewulf config file for node
  template:
    src: wwnodeconf.j2
    dest: /warewulf/config
    owner: root
    group: root
    mode: 0640

- name: add warewulf file sync via cron
  copy:
    src: wwupdatefiles
    dest: /etc/cron.d
    owner: root
    group: root
    mode: 0640

- name: create log output dir for warewulf cron
  file:
    path: /var/log/warewulf
    state: directory
    owner: root
    group: root
    mode: 755

- name: "RUN THESE COMMAND ON OHPC MASTER TO COMPLETE REGISTRATION"
  pause:
    seconds: 1

- name: "sudo wwsh node new ood -y"
  pause:
    seconds: 1

- name: "sudo wwsh node set ood -y -I {{ ood_ip_addr }} --hwadd {{ ood_macaddress }}"
  pause:
    seconds: 1

- name: "sudo wwsh provision set ood -y --files dynamic_hosts,munge.key,slurm.conf"
  pause:
    seconds: 90

- name: Force warewulf synchronization
  shell: /warewulf/bin/wwgetfiles >/var/log/warewulf/wwgetfiles.log 2>&1

- name: start and enable munge
  service:
    name: munge
    state: started
    enabled: yes

- name: start and enable slurmd
  service:
    name: slurmd
    state: started
    enabled: yes

