---
- name: Enable the Software Collections repository
  yum:
    name: "centos-release-scl"
    state: present

- name: Add Open OnDemandâ€™s repository hosted by the Ohio Supercomputer Center
  yum:
    name: "https://yum.osc.edu/ondemand/1.3/ondemand-release-web-1.3-1.el7.noarch.rpm"
    state: present

- name: Install OnDemand and all of its dependencies
  yum:
    name: "ondemand"
    state: present

- name: Open port 80
  firewalld:
    service: http
    permanent: true
    state: enabled

- name: Disable SELinux
  selinux:
    state: disabled

- name: restart machine
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started port=22 delay=15 timeout=300 connect_timeout=15
  become: false

- name: Make sure a service is running
  systemd:
    state: started
    name: httpd24-httpd
    enabled: yes
