---
- name: Enable http service
  systemd:
    name: httpd24-httpd
    enabled: yes

- name: install the latest version of Python
  yum:
    name: python
    state: latest

- name: install the latest version of firewalld
  yum:
    name: firewalld
    state: latest

- name: Open port http/s
  firewalld:
    service: http
    permanent: true
    state: enabled

- firewalld:
    service: https
    permanent: true
    state: enabled

- name: Disable SELinux Enforcement (permissive)
  selinux:
    policy: targeted
    state: permissive

- name: Set SELinux to permissive mode without reboot
  selinux:
    state: disabled
